### ISSUE TITLE
remove transparency in header elements on home page

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.theme#16]
Please change this setting in theme.css:

``` css
.section-isaw-home.template-document_view #portal-top #main-navigation ul#secondary {
  background: rgba(221,217,214,.74);
}
```

to something like this:

``` css
.section-isaw-home.template-document_view #portal-top #main-navigation ul#secondary {
  background: rgba(221,217,214,1);
}
```

**Comment by paregorios** [comment]
And also from this:

``` css
.section-isaw-home.template-document_view #portal-top #main-navigation ul#primary {
  background: rgba(243,243,243,.74);
}
```

to something like this:

``` css
.section-isaw-home.template-document_view #portal-top #main-navigation ul#primary {
  background: rgba(243,243,243,1);
}
```
